// Port of report_redesign_v07.html's Jinja templating + renderer.py's glue —
// builds the report view as an HTML string, then wires up its interactive bits
// (theme toggle, tabs, dimension collapse, sidebar jump, print/download).
//
// IMPORTANT: Jinja auto-escapes {{ }} by default; this does not. Every value that
// originates from the analysis JSON (which is derived from an uploaded PDF's text,
// i.e. attacker-influenceable) is passed through escapeHtml() before insertion.

function escapeHtml(str) {
  if (str === null || str === undefined) return '';
  const div = document.createElement('div');
  div.textContent = String(str);
  return div.innerHTML;
}

function truncate(str, n) {
  if (!str) return '';
  return str.length > n ? str.slice(0, n - 1) + '…' : str;
}

const PROVIDER_LABELS = { anthropic: 'Anthropic', openrouter: 'OpenRouter' };

/**
 * Classifies every citation string across all 9 dimensions' `sources` arrays as
 * coming from the uploaded budget document or from a reference document (CAG/FC),
 * based on the citation text the LLM itself wrote (it's instructed to cite either
 * a page number in the uploaded doc, or a reference filename — see llmClient.js's
 * SOURCING instructions). Purely a text classification of those citations, not an
 * independent verification of them.
 */
function classifySourceProvenance(analysis, referenceData) {
  const refFilenames = (referenceData && referenceData.sources)
    ? referenceData.sources.map((s) => s.filename)
    : [];
  let uploaded = 0, reference = 0, unclear = 0;
  for (const d of DIM_META) {
    const dim = analysis[d.key];
    if (!dim || !Array.isArray(dim.sources)) continue;
    for (const src of dim.sources) {
      const s = String(src);
      if (refFilenames.some((fn) => s.includes(fn))) {
        reference++;
      } else if (/budget document/i.test(s) || /--?\s*page\s*\d/i.test(s) || /\bp\.?\s*\d/i.test(s)) {
        uploaded++;
      } else {
        unclear++;
      }
    }
  }
  const total = uploaded + reference + unclear;
  return { uploaded, reference, unclear, total };
}

function methodologySectionHtml(analysis, filename, pageCount, referenceData, meta, provenance) {
  meta = meta || {};
  const providerLabel = PROVIDER_LABELS[meta.provider] || 'an LLM provider of your choosing';
  const modelLabel = meta.model ? ` (model: ${escapeHtml(meta.model)})` : '';
  const refFilenames = (referenceData && referenceData.sources)
    ? referenceData.sources.map((s) => s.filename)
    : [];

  const provenanceStrip = provenance.total > 0
    ? `<div class="kpi-strip provenance-strip">
        ${kpiValueHtml(`${Math.round((provenance.uploaded / provenance.total) * 100)}%`, 'Cited figures — uploaded document')}
        ${kpiValueHtml(`${Math.round((provenance.reference / provenance.total) * 100)}%`, 'Cited figures — CAG / FC reference reports')}
        ${provenance.unclear ? kpiValueHtml(`${Math.round((provenance.unclear / provenance.total) * 100)}%`, 'Cited, source unclear') : ''}
      </div>
      <p class="methodology-note">Based on a plain-text read of the ${provenance.total} source citations the model attached to its own figures across all 9 dimensions — not an independent re-verification of those figures.</p>`
    : `<p class="methodology-note">This report cited no traceable sources for its figures — treat it with extra caution.</p>`;

  const truncationNote = meta.truncated
    ? `<li><strong>⚠ Uploaded document was truncated</strong> — it ran past the ${(MAX_EXTRACT_CHARS / 1000).toFixed(0)},000-character cap this tool reads per document (${meta.charCount ? meta.charCount.toLocaleString() : 'n/a'} characters were used). Figures from later pages of a long document may be missing from this analysis.</li>`
    : `<li>Uploaded document text (${pageCount} pages${meta.charCount ? `, ${meta.charCount.toLocaleString()} characters` : ''}) was used in full — no truncation.</li>`;

  return `
<div class="section-heading">Methodology &amp; Assumptions</div>
<div class="chart-block notes-block methodology-block">
  <p class="methodology-intro">
    This report was generated by sending the extracted text of <strong>${escapeHtml(filename)}</strong>
    to ${providerLabel}${modelLabel} together with a fixed 9-dimension public-finance analysis framework.
    ${refFilenames.length
      ? `Because this document was identified as ${escapeHtml(analysis.state_name)}'s budget, the model was also
         given ${escapeHtml(analysis.state_name)}'s own <strong>CAG audit report</strong> and
         <strong>Finance Commission report</strong> (${escapeHtml(refFilenames.join(', '))}) as reference context, and
         asked to cross-check figures and benchmarks against them.`
      : `No CAG or Finance Commission reference documents were available for this state, so the analysis is based on
         the uploaded document alone.`}
    The model was instructed to cite a page number or source filename for every figure it states, and to write
    "no official benchmark found" rather than invent one it cannot ground in the document or reference material.
  </p>
  ${provenanceStrip}
  <div class="methodology-assumptions">
    <strong>Key assumptions &amp; limits to know before publishing</strong>
    <ul>
      ${truncationNote}
      <li>Text is extracted directly from the PDF's embedded text layer — there is no OCR step, so a scanned
        (image-only) PDF will extract poorly or not at all, and the model will have little or nothing to analyze.</li>
      <li>The state is auto-detected from the document's own text; reference CAG/FC documents exist for 30 of
        32 states/UTs (not Ladakh or Puducherry as of this build) — analysis proceeds on the uploaded document
        alone when no match is found.</li>
      <li>Reference CAG/FC documents are each capped at roughly 25,000 characters at build time, so very long
        audit or Finance Commission reports are also partially represented, not reproduced in full.</li>
      <li>This is an LLM-generated read of the source material — treat every figure as a lead to verify against
        the primary document before it goes into published, citable work, not as a substitute for that check.</li>
    </ul>
  </div>
</div>`;
}

function trendChartHtml(chart) {
  if (!chart) return '';
  const benchmarkLine = chart.benchmarkY !== null
    ? `<line x1="0" y1="${chart.benchmarkY}" x2="${chart.width}" y2="${chart.benchmarkY}" class="trend-benchmark-line" />`
    : '';
  const dots = chart.dots.map((d) => `<circle cx="${d.x}" cy="${d.y}" r="2.5" class="trend-dot" />`).join('');
  const benchmarkLabel = chart.benchmarkLabel
    ? `<span class="trend-benchmark-label">${escapeHtml(chart.benchmarkLabel)}</span>`
    : '';
  return `
<div class="trend-block">
  <div class="trend-caption">
    <span class="trend-value">${escapeHtml(chart.valueLabel)}</span>
    ${benchmarkLabel}
  </div>
  <svg class="trend-svg" viewBox="0 0 ${chart.width} ${chart.height}" preserveAspectRatio="none">
    ${benchmarkLine}
    <polyline points="${chart.pointsStr}" class="trend-line" />
    ${dots}
  </svg>
  <div class="trend-labels"><span>${escapeHtml(chart.firstLabel)}</span><span>${escapeHtml(chart.lastLabel)}</span></div>
</div>`;
}

function kpiValueHtml(val, label) {
  const isEmpty = !val || String(val).toLowerCase().includes('not available');
  const display = isEmpty ? '<div class="kpi-value na">N/A</div>' : `<div class="kpi-value">${escapeHtml(String(val).split('(')[0].trim())}</div>`;
  return `<div>${display}<div class="kpi-label">${escapeHtml(label)}</div></div>`;
}

function buildReportHtml(analysis, filename, pageCount, referenceData, charts, meta) {
  const a = analysis;
  meta = meta || {};

  let badgeClass = 'caution';
  const fd = ((a.fiscal_position && a.fiscal_position.frbm_status) || '').toLowerCase();
  if (fd.includes('breach')) badgeClass = 'stress';
  else if (fd.includes('compliant')) badgeClass = 'healthy';

  const dimPills = DIM_META.map((d) =>
    `<div class="pill ${d.severity}" data-jump="dim-${d.key}"><span class="sev-dot"></span>${escapeHtml(d.label)}</div>`
  ).join('');

  const execSummary = (a.key_concerns && a.key_positives)
    ? `${escapeHtml(a.state_name)}'s ${escapeHtml(a.fiscal_year)} budget shows ${a.key_concerns.length} key areas of concern and ${a.key_positives.length} positives.
       Own tax revenue covers ${escapeHtml((a.revenue_profile && a.revenue_profile.own_tax_revenue_share) || 'a limited share')} of total receipts,
       while committed expenditure stands at ${escapeHtml((a.committed_expenditure && a.committed_expenditure.total_committed_share) || 'a significant portion')} of revenue receipts —
       leaving limited room for discretionary spending.`
    : `Analysis complete for ${escapeHtml(a.state_name)} ${escapeHtml(a.fiscal_year)}.`;

  const kpis = [
    [(a.fiscal_position && a.fiscal_position.fiscal_deficit_gsdp) || '', 'Fiscal Deficit / GSDP'],
    [(a.debt_sustainability && a.debt_sustainability.debt_gsdp_ratio) || '', 'Debt / GSDP'],
    [(a.committed_expenditure && a.committed_expenditure.total_committed_share) || '', 'Committed Expenditure'],
    [(a.revenue_profile && a.revenue_profile.own_tax_revenue_share) || '', 'Own Tax Revenue Share'],
  ].map(([val, label]) => kpiValueHtml(val, label)).join('');

  const concerns = (a.key_concerns || []).map((c) => `<li>${escapeHtml(c)}</li>`).join('');
  const positives = (a.key_positives || []).map((p) => `<li>${escapeHtml(p)}</li>`).join('');
  const recs = (a.policy_recommendations || []).map((r) => `<li>${escapeHtml(r)}</li>`).join('');

  const dimCards = DIM_META.map((d) => {
    const dim = a[d.key] || {};
    const headline = truncate(dim[d.headline] || '', 70);
    const chartHtml = d.chart ? trendChartHtml(charts[d.chart]) : '';
    const keyStats = (dim.key_stats && dim.key_stats.length)
      ? `<div class="legend">${dim.key_stats.map((s) => `<span class="item">${escapeHtml(s)}</span>`).join('')}</div>`
      : '';
    const benchmark = dim.benchmark
      ? `<div class="dim-benchmark"><strong>Benchmark:</strong> ${escapeHtml(dim.benchmark)}</div>`
      : '';
    const sources = (dim.sources && dim.sources.length)
      ? `<div class="dim-sources"><span class="src-label">Sources</span>${dim.sources.map((s) => `<span class="src-item">${escapeHtml(s)}</span>`).join('')}</div>`
      : '';
    return `
<div class="chart-block dim-block ${d.severity}" id="dim-${d.key}">
  <div class="dim-head">
    <h3>${escapeHtml(d.label)}</h3>
    <span class="dim-toggle">▼</span>
  </div>
  <div class="unit">${escapeHtml(headline)}</div>
  <div class="dim-body">
    ${chartHtml}
    <p class="dim-summary">${escapeHtml(dim.summary || 'No data available.')}</p>
    ${keyStats}
    ${benchmark}
    ${sources}
  </div>
</div>`;
  }).join('');

  const refSourceNames = referenceData && referenceData.sources
    ? referenceData.sources.map((s) => s.filename)
    : [];
  const refSourcesSection = refSourceNames.length
    ? `<div class="section-heading">Reference Sources Used</div>
       <div class="chart-block notes-block"><div class="notes-text">${escapeHtml(refSourceNames.join(' · '))}</div></div>`
    : '';
  const analystNotesSection = a.analyst_notes
    ? `<div class="section-heading">Analyst Notes</div>
       <div class="chart-block notes-block"><strong>Caveats &amp; Data Gaps</strong><div class="notes-text">${escapeHtml(a.analyst_notes)}</div></div>`
    : '';
  const noSourcesSection = (!refSourceNames.length && !a.analyst_notes)
    ? `<div class="chart-block notes-block"><div class="notes-text">No additional sources or analyst notes for this report.</div></div>`
    : '';

  const provenance = classifySourceProvenance(a, referenceData);
  const methodologySection = methodologySectionHtml(a, filename, pageCount, referenceData, meta, provenance);

  const docTypeSummary = a.document_type_summary
    ? `<p class="doc-type-summary">${escapeHtml(a.document_type_summary)}</p>`
    : '';

  return `
<div class="app-shell">
  <aside class="sidebar">
    <h1>State Budget Analyser</h1>
    <p class="subtitle">Public Finance Intelligence</p>

    <div class="sidebar-label">Report</div>
    <div class="meta-card">
      <strong>${escapeHtml(a.state_name)}</strong>
      <span class="fy-pill">FY ${escapeHtml(a.fiscal_year)}</span>
      <span class="meta-line">${escapeHtml(filename)}</span>
      <span class="meta-line">${pageCount} pages · ${escapeHtml(a.analysis_date)}</span>
      ${refSourceNames.length ? `<span class="meta-line">${refSourceNames.length} reference document(s)</span>` : ''}
    </div>

    <div class="sidebar-label">Jump to Dimension</div>
    <div class="pill-col" id="dimJump">${dimPills}</div>

    <div class="sidebar-actions">
      <button class="tool-btn primary" id="btnPrint">🖨 Print Report</button>
      <button class="tool-btn" id="btnDownload">⬇ Download HTML</button>
      <a class="tool-btn" href="https://fiscalplayground.in/state-fiscal-indicators/?theme=playground&category=resource_mobilisation" target="_blank" rel="noopener" title="Opens the State Fiscal Indicators dashboard in a new tab — select ${escapeHtml(a.state_name)} there to see it across all states and years">🔗 Compare ${escapeHtml(a.state_name)} across states &amp; years</a>
      <button class="tool-btn" id="btnNewAnalysis">← New Analysis</button>
    </div>

    <div class="theme-toggle" id="themeToggle" style="margin-top: 8px;">
      <button class="theme-btn" data-theme-choice="storybook">Warm</button>
      <button class="theme-btn" data-theme-choice="playground">Modern</button>
      <button class="theme-btn" data-theme-choice="arcade">Neon</button>
    </div>
  </aside>

  <div class="content-col">
    <div class="sticky-shell">
      <nav class="tabs" id="tabNav">
        <button class="tab-btn active" data-tab="overview">Overview</button>
        <button class="tab-btn" data-tab="analysis">Full Analysis</button>
        <button class="tab-btn" data-tab="sources">Sources &amp; Notes</button>
      </nav>
      <div class="status-bar">
        <span class="status-badge badge-${badgeClass}">${escapeHtml((a.fiscal_position && a.fiscal_position.frbm_status) || 'Under Assessment')}</span>
        <span>${escapeHtml(a.state_name)} · FY ${escapeHtml(a.fiscal_year)}</span>
      </div>
    </div>

    <main>
      <section class="tabpanel" data-panel="overview">
        <div class="state-hero-wrap">
          <div class="state-hero-label">Analyzing</div>
          <div class="state-hero">${escapeHtml(a.state_name)} <span style="font-weight:400; color:var(--muted); font-size:0.6em;">· FY ${escapeHtml(a.fiscal_year)}</span></div>
          ${docTypeSummary}
        </div>

        <div class="chart-block health-block ${badgeClass}">
          <h3>Fiscal Health — ${escapeHtml(a.fiscal_year)}</h3>
          <div class="unit">Overall assessment based on FRBM status, deficit and debt trajectory</div>
          <p class="exec-summary">${execSummary}</p>
          <div class="kpi-strip">${kpis}</div>
        </div>

        <div class="section-heading">What You Need to Know</div>
        <div class="cp-grid">
          <div class="chart-block cp-block concerns">
            <div class="cp-title">Key Concerns</div>
            <ul class="cp-list concerns">${concerns}</ul>
          </div>
          <div class="chart-block cp-block positives">
            <div class="cp-title">Key Positives</div>
            <ul class="cp-list positives">${positives}</ul>
          </div>
        </div>

        <div class="section-heading">Policy Recommendations</div>
        <div class="chart-block recs-block">
          <div class="recs-title">Actionable Recommendations</div>
          <ol class="recs-list">${recs}</ol>
        </div>
      </section>

      <section class="tabpanel hidden" data-panel="analysis">
        <div class="section-heading">Full Analysis — Click any card to expand</div>
        ${dimCards}
      </section>

      <section class="tabpanel hidden" data-panel="sources">
        ${methodologySection}
        ${refSourcesSection}
        ${analystNotesSection}
        ${noSourcesSection}
      </section>
    </main>
  </div>
</div>`;
}

/** Wires up interactivity for the HTML built by buildReportHtml(). Call after inserting it into the DOM. */
function wireReportInteractions(container, onNewAnalysis, htmlForDownload) {
  const root = document.documentElement;
  let savedTheme = 'arcade';
  try { savedTheme = localStorage.getItem('ss-theme') || 'arcade'; } catch (e) {}
  root.dataset.theme = savedTheme;

  function setActiveTheme(theme) {
    container.querySelectorAll('.theme-btn').forEach((b) => {
      b.classList.toggle('active', b.dataset.themeChoice === theme);
    });
  }
  setActiveTheme(savedTheme);

  container.querySelectorAll('.theme-btn').forEach((b) => {
    b.onclick = () => {
      const theme = b.dataset.themeChoice;
      root.dataset.theme = theme;
      try { localStorage.setItem('ss-theme', theme); } catch (e) {}
      setActiveTheme(theme);
    };
  });

  const tabButtons = container.querySelectorAll('.tab-btn');
  const panels = container.querySelectorAll('.tabpanel');
  function showTab(tab) {
    tabButtons.forEach((b) => b.classList.toggle('active', b.dataset.tab === tab));
    panels.forEach((p) => p.classList.toggle('hidden', p.dataset.panel !== tab));
  }
  tabButtons.forEach((b) => { b.onclick = () => showTab(b.dataset.tab); });

  container.querySelectorAll('.dim-block').forEach((el) => {
    el.onclick = () => el.classList.toggle('open');
  });

  container.querySelectorAll('#dimJump .pill').forEach((p) => {
    p.onclick = () => {
      showTab('analysis');
      const target = container.querySelector(`#${p.dataset.jump}`);
      if (target) {
        target.classList.add('open');
        setTimeout(() => target.scrollIntoView({ behavior: 'smooth', block: 'start' }), 30);
      }
    };
  });

  const btnPrint = container.querySelector('#btnPrint');
  if (btnPrint) btnPrint.onclick = () => window.print();

  const btnDownload = container.querySelector('#btnDownload');
  if (btnDownload) {
    btnDownload.onclick = () => {
      const blob = new Blob([htmlForDownload()], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'sorted_summit_report.html';
      link.click();
      URL.revokeObjectURL(url);
    };
  }

  const btnNew = container.querySelector('#btnNewAnalysis');
  if (btnNew) btnNew.onclick = onNewAnalysis;
}
